[package]
name = "ws_srv"
version = "0.1.0"
authors = ["Agapiy Denis <nastvood@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures="0.3"
libc = "0.2"
