[package]
name = "proto_buffer_derive"
version = "0.1.0"
authors = ["Agapiy Denis <nastvood@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true


[dependencies]
proto_buffer = { path = "../" }
quote = "1.0"
syn = { version = "1.0.60", features = ["extra-traits"] }
proc-macro2 = "1.0"
